### ISSUE TITLE
Beta v4

### ISSUE THREAD

**Issue by jseiser** [clowdhaus/terraform-aws-vpc-v4#4]
@bryantbiggs 

Since this repo is no v5, I assume this means the current stable/v3 module is getting ready to move to v4?

Thanks,

**Comment by bryantbiggs** [comment]
correct - you can see more here https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/838#issuecomment-1422596289

The plan is to make a "soft" breaking change (very little to zero changes required by users) for v4 to unlock a number of features folks have been requesting under the current module structure. And the much larger, more disruptive changes would follow after that in a v5. Trying to ensure users can get to the desired functionality without having to go into a major refactor first

**Comment by jseiser** [comment]
Thanks!
